kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "api-gateway.fullname" . }}-server
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.serverConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
